### ISSUE TITLE
CLEVR-XAI-complex publicly available? 

### ISSUE THREAD

**Issue by zfying** [ahmedmagdiosman/clevr-xai#9]
There's only CLEVR-XAI-simple dataset available in the releases section. I'm wondering when will the CLEVR-XAI-complex be publicly available?

**Comment by ArrasL** [comment]
You're right only CLEVR-XAI-simple is available yet. Thanks for your interest and sorry for the delay (my fault)! We will release the complete CLEVR-XAI dataset by end of next week!

**Comment by ahmedmagdiosman** [comment]
Hi @zfying, the dataset is available now! :)
